from __future__ import annotations

STATUS_DOWNLOADED = "downloaded"
STATUS_SKIPPED = "skipped"
STATUS_FAILED = "failed"


DOWNLOAD_STATUSES = (STATUS_DOWNLOADED, STATUS_SKIPPED, STATUS_FAILED)


DEFAULT_CATEGORY = "others"


EXIT_SUCCESS = 0
EXIT_TIMEOUT = 124
EXIT_INTERRUPTED = 130
EXIT_ERROR = 1

__all__ = [
    "STATUS_DOWNLOADED",
    "STATUS_SKIPPED",
    "STATUS_FAILED",
    "DOWNLOAD_STATUSES",
    "DEFAULT_CATEGORY",
    "EXIT_SUCCESS",
    "EXIT_TIMEOUT",
    "EXIT_INTERRUPTED",
    "EXIT_ERROR",
]
